### ISSUE TITLE
Breaking of 3.X api compatiblity

### ISSUE THREAD

**Issue by mleklund** [PowerDNS/pdnscontrol#127]
https://github.com/PowerDNS/pdnscontrol/pull/120 breaks 3.X compatibility with comment "Per @ahupowerdns we're fine with breaking compatibility with 3.x for now.".  Would have saved me a bunch of time any one of the following scnearios had taken place.
1) Update the  README.markdown requirements to be pdns 4.0+
2) Make it backwards compatibly with a setting in pdnscontrol.conf.
3) tag a git version with backward compatibiity

**Comment by akrus** [comment]
+1 :) also spent some time trying to find out what's wrong.

**Comment by zeha** [comment]
Made a tag for the last version speaking 3.x API and clarified current state in the README. Thanks!
