### ISSUE TITLE
Doesn't work with auth 3.4.1 / recursor 3.6.2

### ISSUE THREAD

**Issue by zeha** [PowerDNS/pdnscontrol#92]
Due to X-API-Key.

**Comment by cheribral** [comment]
I see that this has been sitting for a little while.  Any chance we could get an update on when this might be fixed, or if help is needed?

**Comment by zeha** [comment]
We added a workaround for setups that use pdnsmgrd with passthrough authentication. Proper support in pdnscontrol is still to be done; there was someone working on it, but I can't remember the details right now.

**Comment by fincham** [comment]
I have a local branch where this works, but I need time to tidy it up before I can make a pull request. Hopefully I can work on this in the next month or so....

**Comment by cheribral** [comment]
Awesome, cheers!

**Comment by fincham** [comment]
Hurrah! Thanks zeha, even better than my patch :)
