### ISSUE TITLE
Parsing record content: expected digits at position 0

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdnscontrol#96]
![jmbp-1342](https://cloud.githubusercontent.com/assets/60706/5892358/6badc336-a4bc-11e4-9198-79a6f8a984a7.png)

I really don't know what that means. 
FYI: same message without trailing period on rdata.

**Comment by zeha** [comment]
I can't easily reproduce this, but I noticed an interesting thing in your screenshot: the 'Name' for those SOA, NS and MX records should show up as '$ORIGIN'... Maybe related.

**Comment by zeha** [comment]
This should be working in recent versions (thanks @mind04)

**Comment by pshanmu** [comment]
I have similar problem - can some one please help me.

root@ns2:~ # curl -X PATCH --data '{"rrsets": [ {"name":"sparrowdesk.com.", "type":"MX", "ttl":300, "changetype":"REPLACE", "records": [ {"name":"cherry.sparrowdesk.com", "type":"MX", "content":"mta1.sparrowdesk.com", "disabled":false, "priority": 10 } ] } ] }' -H 'X-API-Key: CherrySGP1' http://128.199.128.109:8081/api/v1/servers/localhost/zones/sparrowdesk.com | jq .
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   396  100   171  100   225   3339   4394 --:--:-- --:--:-- --:--:--  4591
{
  "error": "Record sparrowdesk.com./MX 'mta1.sparrowdesk.com': Parsing record content (try 'pdnsutil check-zone'): expected digits at position 0 in 'mta1.sparrowdesk.com'"
}

**Comment by pshanmu** [comment]
root@ns2:~ # pdns_control version
4.0.1
And powerDns is running in FreeBSD 10.3
- Shanmu

**Comment by zeha** [comment]
- pshanmu notifications@github.com [160916 07:20]:
  > I have similar problem - can some one please help me.
  > 
  > root@ns2:~ # curl -X PATCH --data '{"rrsets": [ {"name":"sparrowdesk.com.", "type":"MX", "ttl":300, "changetype":"REPLACE", "records": [ {"name":"cherry.sparrowdesk.com", "type":"MX", "content":"mta1.sparrowdesk.com", "disabled":false, "priority": 10 } ] } ] }' -H 'X-API-Key: CherrySGP1' http://128.199.128.109:8081/api/v1/servers/localhost/zones/sparrowdesk.com | jq .

You are sending an API request formatted for PowerDNS 3.x to a 4.x
instance; please see the docs for the correct format/changes (in
particular: priority field has been removed).

C.

**Comment by pshanmu** [comment]
Hi Christian,

Thanks for pointing it out.

-Shanmu
