### ISSUE TITLE
Export zone fails

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdnscontrol#97]
![jmbp-1343](https://cloud.githubusercontent.com/assets/60706/5892374/dd5f36a4-a4bc-11e4-923d-bc18870ed211.png)

**Comment by jpmens** [comment]
Don't mind the stupid zone name; it is for my internal testing only.

**Comment by zeha** [comment]
Can reproduce, don't understand what's going on yet.

**Comment by zeha** [comment]
Fixed in 1ecc8b5
