### ISSUE TITLE
Update from master and flush cache fails

### ISSUE THREAD

**Issue by jpmens** [PowerDNS/pdnscontrol#98]
![jmbp-1344](https://cloud.githubusercontent.com/assets/60706/5892417/8f8da5c2-a4bd-11e4-9b99-cd2777568845.png)

It is unclear what fails. Some sort of comms with pdnscontrol, the AXFR, ... ?

**Comment by zeha** [comment]
pdnscontrol still talks to /jsonstat for these commands, but /jsonstat doesn't understand X-API-Key. Meh.

**Comment by zeha** [comment]
PowerDNS/pdns/pull/2127
